[tool.uv.workspace]
members = ["metamon"]

[tool.uv.sources]
metamon = { workspace = true }

[project]
name = "evio-lite-v1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flax>=0.12.7",
    "jax>=0.10.0",
    "jaxlib>=0.10.0",
    "optax>=0.2.8",
    "pandas>=3.0.3",
    "metamon"
]
